name: Promeritum
favicon: null
layout_spectrum: 0.50881
typography_spectrum: 0.85
title: Promeritum Consultancy Limited
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#58595b'
    - '#dbdcdd'
    - '#a1a1a1'
    - '#8dc641'
  brandStrength: 0.875
  lightness: 0.4375
  saturation: 0.6661675663199276
  rhythmicContrast: 0.7612436909694225
purpose: []
